### ISSUE TITLE
php72w-pecl-redis rpm not installing due to missing depency

### ISSUE THREAD

**Issue by noone1337** [webtatic-rpms/php7-pecl-redis#1]
Hi,

since a few days php72w-pecl-redis package could not be installed as php72w-pecl-igbinary (which is a depency) is missing in repo.
Can you please check why it's missing?

THX, Robert

**Comment by andytson** [comment]
It was an unintentional effect of archiving old versions of packages. It is resolved now

**Comment by noone1337** [comment]
Hi @andytson ,

It's still missing for php 7.2 and higher ...

```
# yum list php*-pecl-igbinary --showduplicates
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * epel: mirror.imt-systems.com
 * webtatic: uk.repo.webtatic.com
366 packages excluded due to repository priority protections
Available Packages
php-pecl-igbinary.x86_64                                       1.2.1-1.el7                                    epel
php55w-pecl-igbinary.x86_64                                    2.0.1-1.w7                                     webtatic
php56w-pecl-igbinary.x86_64                                    2.0.5-1.w7                                     webtatic
php70w-pecl-igbinary.x86_64                                    2.0.5-1.w7                                     webtatic
php71w-pecl-igbinary.x86_64                                    2.0.5-1.w7                                     webtatic
```
Can you check again?
